logger:
    name: DefaultLogger
    parent_log_dir: ./logs
    forced_log_id: -1
    log_streams_to_file: false
scheduler:
    name: SLURMScheduler
    cleanup_cmd: module purge
    option_cmd: ["--job-name=GrNewt",
                 "--time=2:00:00", # TODO dev=02:00:00 ; gpu-t3=20:00:00 ; gpu-t4=100:00:00
                 "--qos=qos_gpu-dev", #TODO qos_gpu-dev (2 h) ; qos_gpu-t3 (20 h) ; qos_gpu-t4 (200 h)
                 "--partition=gpu_p13", #TODO
                 "--gres=gpu:1",
                 "--cpus-per-task=10", #TODO
                 "--nodes=1",
                 "--ntasks-per-node=1",
                 "--hint=nomultithread",
                 "--error=AAA-err-%j.txt",
                 "--output=AAA-out-%j.txt"
    ]
    shell_config_cmd: source ~/.bashrc
    shell_path: /bin/bash
    env_cmd: module load pytorch-gpu/py3/2.1.1
version_manager:
    name: GitVM
    parent_work_dir: ./.workdir
    compute_requirements: false
use_version_manager: false
use_scheduler: false
use_logger: true
interactive_mode: false
